In [26]:
import numpy as np
from tqdm import tqdm 

# 1.Numpy

행렬이나 일반적으로 대규모 다차원 배열을 쉽게 처리할 수 있도록 지원하는 파이썬의 라이브러리

references: 
- [numpy](https://numpy.org/doc/stable/reference/index.html#reference)
- [cs231 numpy](https://cs231n.github.io/python-numpy-tutorial/)
- [Python For Data Science Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

<br>

numpy 특징 <br>
- 파이썬 리스트에 비해 빠르고, 메모리 효율적
- 반복문 없이 배열에 대한 처리 지원
- 다양한 기능 제공
<br>
<br>

numpy 기능 <br>
- 1. shape: numpy dimension
- 2. ndim: shape에서 얼마나 나오는지
- 3. dtype: numpy 원소의 데이터 타입

## 1.1 배열 생성

### 1.1.1 기본 배열 생성

#### arange
일정 범위의 배열을 생성 <br>
python의 range와 유사 <br>
단, arange는 실수 사용 가능 <br>

> 주의 <br>
np.arange(-3, 3, 0.5, dtype=int) <br>
array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

<br>

사용법
```python
x = np.arange(0, 10)
x = np.arange(-5, 5, 0.5)
```

In [3]:
np.arange(-3, 3, 0.5)

array([-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
        2.5])

In [7]:
ranks = np.random.choice(np.arange(1,101),size=100)
ranks

array([ 55,  28,  59,  31,  51,   1,  38,  58,   8,  71,  97,  71,  97,
        93,  32,  51,  72,  79,  69,  30,  80,  36,  24,   1,  32,  86,
        19,  40, 100,  41,  14,  17,  54,  88,  50,  76,   5,  76,  15,
         9,   3,  69,  43,  61,  26,  80,  98,  19,  67,  74,  49,  16,
        39,  51,  89,  89,  72,  60,  14,  62,  94,  59,  29,  43,  15,
        39,  56,  64,  83,  28,  14,  32,  36,  37,  64,  72,  10,   7,
        40,  50,   6,  24,  16,  65,  73,  68,  34,   7,  99,  22,  95,
        92,  40,  88,  55,  39,  21,  12,  32,  13])

In [10]:
((ranks-1)//20)+1

array([3, 2, 3, 2, 3, 1, 2, 3, 1, 4, 5, 4, 5, 5, 2, 3, 4, 4, 4, 2, 4, 2,
       2, 1, 2, 5, 1, 2, 5, 3, 1, 1, 3, 5, 3, 4, 1, 4, 1, 1, 1, 4, 3, 4,
       2, 4, 5, 1, 4, 4, 3, 1, 2, 3, 5, 5, 4, 3, 1, 4, 5, 3, 2, 3, 1, 2,
       3, 4, 5, 2, 1, 2, 2, 2, 4, 4, 1, 1, 2, 3, 1, 2, 1, 4, 4, 4, 2, 1,
       5, 2, 5, 5, 2, 5, 3, 2, 2, 1, 2, 1], dtype=int32)

#### linspace

arange와 유사 <br>
start와 stop를 주어진 숫자 만큼 분할

<br>

사용법
```python
x = np.linspace(2, 3, num=5)
x = np.linspace(2, 3, num=5, endpoint=False)    # 끝 점 미포함 
```

In [13]:
np.linspace(2,3, num =5)
np.linspace(2,3, num =5, endpoint= False)

array([2. , 2.2, 2.4, 2.6, 2.8])

#### eye

대각행렬이 1이고 나머지가 0인 행렬 생성 <br>
k를 이용하여 1의 위치를 조정할 수 있음 <br>
<br>

사용법
```python
x = np.eye(10)    # np.identity와 동일
x = np.eye(10, k =1)
```

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### zeros

shape을 입력하면 모든 값이 0인 해당 shape에 맞는 배열 생성 <br>

사용법
```python
x = np.zeros(5)
x = np.zeros((5, 2), dtype=float)
```

In [15]:
np.zeros(4)

array([0., 0., 0., 0.])

#### ones

shape을 입력하면 모든 값이 1인 해당 shape에 맞는 배열 생성 <br>
<br>

사용법
```python
x = np.ones(5)
x = np.ones((5, 2), dtype=float)
```

#### full

shape과 숫자를 입력하면 입력한 숫자로 찬 해당 shape에 맞는 배열 생성 <br>
<br>

사용법
```python
x = np.full(5, np.inf)
x = np.full((5, 2), np.nan)
```

In [17]:
np.full((5,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

#### tril

lower triangle matrix 생성 <br>
m값을 이용하여 삼각행렬 이동 가능 <br>
<br>

사용법
```python
x = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
```

In [19]:
x = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x

array([[ 1,  0,  0],
       [ 4,  5,  0],
       [ 7,  8,  9],
       [10, 11, 12]])

#### triu

upper triangle matrix 생성 <br>
m값을 이용하여 삼각행렬 이동 가능 <br>
<br>

사용법
```python
x = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)
```

### 1.1.2 랜덤 배열 생성

#### random

균등분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.random(size=(2, 3))    # size: dim
```

#### randint

지정한 범위 내에서 임의의 수 생성

사용법
```python
x = np.random.randint(0, 10, size=(5,2))    # size: dim
```

In [24]:
np.random.random(size=(2,3))

x = np.random.randint(0,10,size=(5,2))
x

array([[2, 5],
       [2, 3],
       [0, 7],
       [0, 7],
       [8, 0]])

In [33]:
def lotto(money,win_numbers):
    numbers=np.random.randint(1,46, size = (money//1000,6))
    win_count = 0

    for num in tqdm(numbers):
        num.sort()
        if list(num) == win_numbers:
            win_count += 1
        
    return win_count

In [34]:
lotto(100000,[16,21,25,36,38,42])

100%|██████████| 100/100 [00:00<00:00, 100054.96it/s]


0

#### normal

정규분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.normal(loc=0, scale=1, size=(2, 3))
# loc: 평균
# scale: 분산
# size: dim
```

#### randn

표준정규분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.randn(2, 3)
```

In [35]:
np.random.randn(2,3,4)

array([[[ 0.48920698,  0.55836985, -0.49852943, -0.43525307],
        [ 2.22353148,  1.46482219, -0.3841479 ,  0.89481638],
        [ 0.29692022, -0.45075281, -0.45199137,  0.04206558]],

       [[ 0.80042903,  0.98110868, -0.01128744,  0.68644771],
        [ 0.23383401,  1.15299627,  1.16282644, -1.02602981],
        [-1.92450806,  0.43559585,  1.85668371,  0.66812037]]])

## 1.2 배열 조작

### 1.2.1 배열 결합

#### concatenate

두 배열을 결합 <br>
<br>

사용법 
```python
a = np.arange(12).reshape(2, 6)
b = np.arange(12).reshape(2, 6)
np.concatenate([a, b], axis=0)
np.concatenate([a, b], axis=1)
```

In [37]:
a = np.arange(12).reshape(2, 6)
b = np.arange(12).reshape(2, 6)
np.concatenate([a, b], axis=0)
#np.concatenate([a, b], axis=1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [38]:
x = np.arange(9)
print(np.split(x,3))
print(np.split(x,[3,5,6,10]))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7, 8]), array([], dtype=int32)]


### 1.2.2 배열 분할

#### array_split

주어진 배열을 분할 <br>
<br>

사용법
```python
x = np.arange(9.0)
np.split(x, 3)
np.split(x, [3, 5, 6, 10])
```

### 1.2.3 차원 변경

#### reshape

배열의 모양을 원하는 형태로 바꿈 <br>
단, 바꾸는 배열의 차원 곱은 원 배열의 차원 곱과 일치해야 함 <br>
<br>

사용법
```python
x = np.arange(30)
x.reshape(5, 6)
```


#### flatten

배열을 1차원 배열로 바꿈 <br>
<br>
사용법 <br>
```python
x = np.arange(30).reshape(2, 5, 3)
x.flatten()
```

In [39]:
x = np.arange(30).reshape(2, 5, 3)
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### squeeze

불필요한 차원을 제거 <br>
즉, 길이가 0인 차원을 제거 <br>
<br>

사용법
```python
x = np.arange(10).reshape(10, 1, 1)
x.squeeze()
```

In [40]:
x = np.arange(10).reshape(10, 1, 1)
x.squeeze()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### expand_dims

차원 추가 <br>
<br>

사용법
```python
x = np.arange(10)
np.expand_dims(x, 0)
```

### 1.2.4 모양 변경

##### roll

배열을 입력한 수 만큼 이동 <br>
<br>

사용법
```python
x = np.arange(10)
np.roll(x, 2)
```

```python
x = np.reshape(x, (2, 5))
np.roll(x, 1)
np.roll(x, -1, axis=0)
np.roll(x, -1, axis=1)
```

In [41]:
x = np.arange(10)
np.roll(x, 2)

array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

In [43]:
x = np.reshape(x, (2, 5))
print(np.roll(x, 1))
print(np.roll(x, -1, axis=0))
print(np.roll(x, -1, axis=1))

[[9 0 1 2 3]
 [4 5 6 7 8]]
[[5 6 7 8 9]
 [0 1 2 3 4]]
[[1 2 3 4 0]
 [6 7 8 9 5]]


##### flip

지정된 축을 기준으로 배열을 뒤집음 <br>
<br>

사용법

```python
x = np.arange(10).reshape(5, 2)
np.flip(x, 0)
```


In [46]:
x = np.arange(20).reshape(4,5)
print(x)
print("-------------")
print(np.flip(x, axis = 0))
print("-------------")
print(np.flip(x, axis = 1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
-------------
[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
-------------
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]


### 1.2.5 축 변경

#### swapaxes

두 축의 위치를 지정하여 변경 <br>
<br>

사용법
```python
x = np.arange(100).reshape(5, 2, 10)
x.swapaxis(0, 2)    # 0 <-> 2
```

#### transpose

여러 축의 위치를 변경 <br>
transpose에 들어가는 인자는 축의 순서 <br>
<br>

사용법

```python
x = np.arange(100).reshape(5, 2, 10)
x.transpose(0, 2, 1)    # 1번 축과 2번 축을 바꿈
x.transpose(2, 0, 1)    # 2->0, 0->1, 1->2
```

### 1.2.6 배열 정렬

#### sort

주어진 축을 기준으로 배열 정렬 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
x.sort(axis=1)
x
```



In [50]:
x = np.random.randint(0, 20, (5, 4))
print(x)
print("------------------")
x.sort(axis=0)
print(x)
print("------------------")
x.sort(axis=1)
print(x)

[[ 8 13 12  0]
 [ 1 16  6 19]
 [ 7  9  9  9]
 [19  3  2  1]
 [18 14 15 10]]
------------------
[[ 1  3  2  0]
 [ 7  9  6  1]
 [ 8 13  9  9]
 [18 14 12 10]
 [19 16 15 19]]
------------------
[[ 0  1  2  3]
 [ 1  6  7  9]
 [ 8  9  9 13]
 [10 12 14 18]
 [15 16 19 19]]


#### argsort

주어진 축을 기준으로 정렬된 배열의 인덱스 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
x.argsort(axis=1)
```


In [51]:
x = np.random.randint(0,10,10)
print(x)
print(x.argsort())

[1 5 4 0 1 7 5 6 2 9]
[3 0 4 8 2 1 6 7 5 9]


### 1.2.7 기타

##### unique

배열 내의 중복값 제거 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
np.unique(x, axis=0)
```

In [53]:
x = np.random.randint(0,10,10)
print(x)
print(np.unique(x))

[5 9 7 4 4 0 5 6 0 9]
[0 4 5 6 7 9]


#### nan_to_num

배열 내의 nan 값을 특정 숫자로 변환 <br>
<br>

사용법
```python
x = np.full((3, 4), np.nan)
np.nan_to_num(x, nan=1)


In [55]:
x = np.full((2, 3), np.nan)
np.nan_to_num(x, nan=1)

array([[1., 1., 1.],
       [1., 1., 1.]])

#### trim_zeros

배열 내의 0값을 제거 <br>
<br>

사용법
```python
x = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
np.trip_zeros(x, trip='f')    # 앞의 0만 제거
np.trip_zeros(x, trip='b')    # 뒤의 0만 제거
np.trip_zeros(x, trip='fb')   # 앞뒤 0 제거
```

In [56]:
x = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
np.trip_zeros(x, trip='f')    # 앞의 0만 제거
np.trip_zeros(x, trip='b')    # 뒤의 0만 제거
np.trip_zeros(x, trip='fb')   # 앞뒤 0 제거

AttributeError: module 'numpy' has no attribute 'trip_zeros'

stride_tricks

배열을 주어진 윈도우 만큼 분할 <br>
<br>

사용법
```python
x = np.arange(10)
y = np.lib.stride_tricks.sliding_window_view(x, 3)
```

In [58]:
x = np.arange(10)
y = np.lib.stride_tricks.sliding_window_view(x, 3)
y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

## 1.3 배열 탐색

### argmax

축을 기준으로 배열에서 최댓걊의 index 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.argmax(x)
np.argmax(x, axis=0)
```

### argmin

축을 기준으로 배열에서 최솟걊의 index 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.argmin(x)
np.argmin(x, axis=0)
```



### where

특정 조건에 맞는 값의 index 반환 또는 값 변환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.where(x < 5)    # 조건을 만족하는 값의 인덱스 반환
np.where(x < 5, 1, 0)    # x가 5보다 작은 값은 1, 그렇지 않으면 0
```

In [59]:

x = np.arange(6).reshape(2,3)
print(x)
np.where(x < 5)    # 조건을 만족하는 값의 인덱스 반환
np.where(x < 5, 1, 0) 

[[0 1 2]
 [3 4 5]]


array([[1, 1, 1],
       [1, 1, 0]])

### extract

특정 조건에 맞는 값을 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.extract(x > 2, x)
```

In [60]:
x = np.arange(6).reshape(2,3)
np.extract(x > 2, x)

array([3, 4, 5])

##  1.4 배열 연산

### matmul

행렬 곱 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
y = np.random.randint(0, 10, size=(2,2))

np.matmul(x, y)
x @ y
```

In [64]:
x = np.random.randint(0, 10, size=(2,2))
y = np.random.randint(0, 10, size=(2,2))

print(x)
print(y)
print(np.matmul(x, y))
print (x @ y)

[[1 7]
 [9 0]]
[[6 1]
 [6 7]]
[[48 50]
 [54  9]]
[[48 50]
 [54  9]]


### eigen

eigenvalue, eigenvector 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.eig(x)
```



In [66]:
x = np.random.randint(0, 10,size= (2,2))
np.linalg.eig(x)

(array([9.14005494, 1.85994506]),
 array([[ 0.98699564, -0.75177487],
        [ 0.16074704,  0.65941986]]))

### det

배열의 행렬식을 구함 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.det(x)
```

### trace
대각원소의 합 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.trace(x)
```

### solve

선형 방정식의 해를 반환 <br>
<br>


사용법
```python
#  x_0 + 2*x_1 = 1
# 3x_0 + 5*x_1 = 2:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
np.linalg.solve(a, b)
```

inv

선형 방정식의 해를 반환 <br>
<br>


사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.inv(x)
```

## 1.5 통계 함수

#### ptp

축별 최댓값 - 최솟값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.ptp(axis=0)
```

In [67]:
x = np.arange(12).reshape(4,3)

print(x)
x.ptp(axis=0)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([9, 9, 9])

#### median

축별 중앙값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
np.median(x, axis=0)
```

### sum

축별 합 산출 <br>
<br>

사용법
```python
x = np.array([3, 4, 5])
x.sum(axis=1)
```

### average

축별 가중합 산출 <br>
<br>

사용법
```python
x = np.array([3, 4, 5])
np.average(x, weights=[0.5, 0.3, 0.2])
```

### mean

축별 평균 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.mean(axis=1)
```

### min

축별 최솟값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.min(axis=1)
```

### min

축별 최댓값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.max(axis=1)
```

### std
축별 표준편차 산출 <br>
<br>

사용법

```python
x = np.arange(12).reshape(4,3)
x.std(axis=1)
```

### cov

공분산 산출 <br>
<br>

사용법
```python
x = np.random.rand(25).reshape(5, 5)
np.cov(x)
```